# Generated by Django 4.1.1 on 2022-09-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rasaweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="Area_of_Interest",
            field=models.CharField(default="Python", max_length=30),
        ),
        migrations.AddField(
            model_name="account",
            name="Domain",
            field=models.CharField(
                choices=[
                    ("Business Finance", "Business Finance"),
                    ("Graphic Design", "Graphic Design"),
                    ("Musical Instruments", "Musical Instruments"),
                    ("Web Development", "Web Development"),
                ],
                default="Business Finance",
                max_length=25,
            ),
        ),
    ]
